"""empty message

Revision ID: fe53bf7783ee
Revises: ed53b1f6ff6d
Create Date: 2018-06-07 15:01:43.461626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe53bf7783ee'
down_revision = 'ed53b1f6ff6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('photo_1', sa.String(200), nullable=True))
    op.add_column('t_user', sa.Column('photo_2', sa.String(200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'photo_2')
    op.drop_column('t_user', 'photo_1')
    # ### end Alembic commands ###
